<Project>

  <PropertyGroup>
    <MicrosoftNetTestSdkVersion>18.4.0</MicrosoftNetTestSdkVersion>
    <XunitAnalyzersVersion>2.0.0-pre.40</XunitAnalyzersVersion>
    <XunitV2Version>2.9.3</XunitV2Version>
    <XunitV3Version>4.0.0-pre.81</XunitV3Version>
    <XunitRunnerVSVersion>4.0.0-pre.4</XunitRunnerVSVersion>
  </PropertyGroup>

</Project>
